# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'usbHidTool.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(868, 461)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_hid_devices = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_hid_devices.setObjectName("comboBox_hid_devices")
        self.verticalLayout.addWidget(self.comboBox_hid_devices)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_vid = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_vid.setReadOnly(True)
        self.lineEdit_vid.setObjectName("lineEdit_vid")
        self.horizontalLayout_2.addWidget(self.lineEdit_vid)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit_vname = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_vname.setReadOnly(True)
        self.lineEdit_vname.setObjectName("lineEdit_vname")
        self.horizontalLayout_4.addWidget(self.lineEdit_vname)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_pid = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pid.setReadOnly(True)
        self.lineEdit_pid.setObjectName("lineEdit_pid")
        self.horizontalLayout_3.addWidget(self.lineEdit_pid)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lineEdit_pname = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pname.setReadOnly(True)
        self.lineEdit_pname.setObjectName("lineEdit_pname")
        self.horizontalLayout_5.addWidget(self.lineEdit_pname)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.lineEdit_sn = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_sn.setReadOnly(True)
        self.lineEdit_sn.setObjectName("lineEdit_sn")
        self.horizontalLayout_8.addWidget(self.lineEdit_sn)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_30.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_refresh = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_refresh.sizePolicy().hasHeightForWidth())
        self.pushButton_refresh.setSizePolicy(sizePolicy)
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.horizontalLayout_9.addWidget(self.pushButton_refresh)
        self.pushButton_copy_path = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_copy_path.sizePolicy().hasHeightForWidth())
        self.pushButton_copy_path.setSizePolicy(sizePolicy)
        self.pushButton_copy_path.setObjectName("pushButton_copy_path")
        self.horizontalLayout_9.addWidget(self.pushButton_copy_path)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.pushButton_Open = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Open.sizePolicy().hasHeightForWidth())
        self.pushButton_Open.setSizePolicy(sizePolicy)
        self.pushButton_Open.setMaximumSize(QtCore.QSize(16000000, 16000000))
        self.pushButton_Open.setObjectName("pushButton_Open")
        self.verticalLayout_2.addWidget(self.pushButton_Open)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_30.addLayout(self.verticalLayout_2)
        self.horizontalLayout_30.setStretch(0, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_30)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_one_cmd = QtWidgets.QWidget()
        self.tab_one_cmd.setObjectName("tab_one_cmd")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_one_cmd)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_input = QtWidgets.QLineEdit(self.tab_one_cmd)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.verticalLayout_3.addWidget(self.lineEdit_input)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.checkBox_hex = QtWidgets.QCheckBox(self.tab_one_cmd)
        self.checkBox_hex.setObjectName("checkBox_hex")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBox_hex)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_7 = QtWidgets.QLabel(self.tab_one_cmd)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_27.addWidget(self.label_7)
        self.lineEdit_report_id = QtWidgets.QLineEdit(self.tab_one_cmd)
        self.lineEdit_report_id.setObjectName("lineEdit_report_id")
        self.horizontalLayout_27.addWidget(self.lineEdit_report_id)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_27)
        self.checkBox_timer = QtWidgets.QCheckBox(self.tab_one_cmd)
        self.checkBox_timer.setObjectName("checkBox_timer")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkBox_timer)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_6 = QtWidgets.QLabel(self.tab_one_cmd)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_28.addWidget(self.label_6)
        self.lineEdit_time = QtWidgets.QLineEdit(self.tab_one_cmd)
        self.lineEdit_time.setObjectName("lineEdit_time")
        self.horizontalLayout_28.addWidget(self.lineEdit_time)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_28)
        self.horizontalLayout_26.addLayout(self.formLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_26.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_26.addItem(spacerItem2)
        self.pushButton_send = QtWidgets.QPushButton(self.tab_one_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_send.sizePolicy().hasHeightForWidth())
        self.pushButton_send.setSizePolicy(sizePolicy)
        self.pushButton_send.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_send.setAutoFillBackground(True)
        self.pushButton_send.setObjectName("pushButton_send")
        self.horizontalLayout_26.addWidget(self.pushButton_send)
        self.horizontalLayout_26.setStretch(0, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_26)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab_one_cmd, "")
        self.tab_more_cmd = QtWidgets.QWidget()
        self.tab_more_cmd.setObjectName("tab_more_cmd")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_more_cmd)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_29.setSpacing(7)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEdit_ex_1 = QtWidgets.QLineEdit(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ex_1.sizePolicy().hasHeightForWidth())
        self.lineEdit_ex_1.setSizePolicy(sizePolicy)
        self.lineEdit_ex_1.setObjectName("lineEdit_ex_1")
        self.horizontalLayout_10.addWidget(self.lineEdit_ex_1)
        self.pushButton_ex_1 = QtWidgets.QPushButton(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ex_1.sizePolicy().hasHeightForWidth())
        self.pushButton_ex_1.setSizePolicy(sizePolicy)
        self.pushButton_ex_1.setObjectName("pushButton_ex_1")
        self.horizontalLayout_10.addWidget(self.pushButton_ex_1)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineEdit_ex_2 = QtWidgets.QLineEdit(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ex_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_ex_2.setSizePolicy(sizePolicy)
        self.lineEdit_ex_2.setObjectName("lineEdit_ex_2")
        self.horizontalLayout_11.addWidget(self.lineEdit_ex_2)
        self.pushButton_ex_2 = QtWidgets.QPushButton(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ex_2.sizePolicy().hasHeightForWidth())
        self.pushButton_ex_2.setSizePolicy(sizePolicy)
        self.pushButton_ex_2.setObjectName("pushButton_ex_2")
        self.horizontalLayout_11.addWidget(self.pushButton_ex_2)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lineEdit_ex_3 = QtWidgets.QLineEdit(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ex_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_ex_3.setSizePolicy(sizePolicy)
        self.lineEdit_ex_3.setObjectName("lineEdit_ex_3")
        self.horizontalLayout_12.addWidget(self.lineEdit_ex_3)
        self.pushButton_ex_3 = QtWidgets.QPushButton(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ex_3.sizePolicy().hasHeightForWidth())
        self.pushButton_ex_3.setSizePolicy(sizePolicy)
        self.pushButton_ex_3.setObjectName("pushButton_ex_3")
        self.horizontalLayout_12.addWidget(self.pushButton_ex_3)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lineEdit_ex_4 = QtWidgets.QLineEdit(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ex_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_ex_4.setSizePolicy(sizePolicy)
        self.lineEdit_ex_4.setObjectName("lineEdit_ex_4")
        self.horizontalLayout_13.addWidget(self.lineEdit_ex_4)
        self.pushButton_ex_4 = QtWidgets.QPushButton(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ex_4.sizePolicy().hasHeightForWidth())
        self.pushButton_ex_4.setSizePolicy(sizePolicy)
        self.pushButton_ex_4.setObjectName("pushButton_ex_4")
        self.horizontalLayout_13.addWidget(self.pushButton_ex_4)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lineEdit_ex_5 = QtWidgets.QLineEdit(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ex_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_ex_5.setSizePolicy(sizePolicy)
        self.lineEdit_ex_5.setObjectName("lineEdit_ex_5")
        self.horizontalLayout_14.addWidget(self.lineEdit_ex_5)
        self.pushButton_ex_5 = QtWidgets.QPushButton(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ex_5.sizePolicy().hasHeightForWidth())
        self.pushButton_ex_5.setSizePolicy(sizePolicy)
        self.pushButton_ex_5.setObjectName("pushButton_ex_5")
        self.horizontalLayout_14.addWidget(self.pushButton_ex_5)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.lineEdit_ex_6 = QtWidgets.QLineEdit(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ex_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_ex_6.setSizePolicy(sizePolicy)
        self.lineEdit_ex_6.setObjectName("lineEdit_ex_6")
        self.horizontalLayout_15.addWidget(self.lineEdit_ex_6)
        self.pushButton_ex_6 = QtWidgets.QPushButton(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ex_6.sizePolicy().hasHeightForWidth())
        self.pushButton_ex_6.setSizePolicy(sizePolicy)
        self.pushButton_ex_6.setObjectName("pushButton_ex_6")
        self.horizontalLayout_15.addWidget(self.pushButton_ex_6)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.lineEdit_ex_7 = QtWidgets.QLineEdit(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ex_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_ex_7.setSizePolicy(sizePolicy)
        self.lineEdit_ex_7.setObjectName("lineEdit_ex_7")
        self.horizontalLayout_16.addWidget(self.lineEdit_ex_7)
        self.pushButton_ex_7 = QtWidgets.QPushButton(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ex_7.sizePolicy().hasHeightForWidth())
        self.pushButton_ex_7.setSizePolicy(sizePolicy)
        self.pushButton_ex_7.setObjectName("pushButton_ex_7")
        self.horizontalLayout_16.addWidget(self.pushButton_ex_7)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.lineEdit_ex_8 = QtWidgets.QLineEdit(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ex_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_ex_8.setSizePolicy(sizePolicy)
        self.lineEdit_ex_8.setObjectName("lineEdit_ex_8")
        self.horizontalLayout_17.addWidget(self.lineEdit_ex_8)
        self.pushButton_ex_8 = QtWidgets.QPushButton(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ex_8.sizePolicy().hasHeightForWidth())
        self.pushButton_ex_8.setSizePolicy(sizePolicy)
        self.pushButton_ex_8.setObjectName("pushButton_ex_8")
        self.horizontalLayout_17.addWidget(self.pushButton_ex_8)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_17)
        self.verticalLayout_5.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.lineEdit_ex_9 = QtWidgets.QLineEdit(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ex_9.sizePolicy().hasHeightForWidth())
        self.lineEdit_ex_9.setSizePolicy(sizePolicy)
        self.lineEdit_ex_9.setObjectName("lineEdit_ex_9")
        self.horizontalLayout_18.addWidget(self.lineEdit_ex_9)
        self.pushButton_ex_9 = QtWidgets.QPushButton(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ex_9.sizePolicy().hasHeightForWidth())
        self.pushButton_ex_9.setSizePolicy(sizePolicy)
        self.pushButton_ex_9.setObjectName("pushButton_ex_9")
        self.horizontalLayout_18.addWidget(self.pushButton_ex_9)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.lineEdit_ex_10 = QtWidgets.QLineEdit(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ex_10.sizePolicy().hasHeightForWidth())
        self.lineEdit_ex_10.setSizePolicy(sizePolicy)
        self.lineEdit_ex_10.setObjectName("lineEdit_ex_10")
        self.horizontalLayout_19.addWidget(self.lineEdit_ex_10)
        self.pushButton_ex_10 = QtWidgets.QPushButton(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ex_10.sizePolicy().hasHeightForWidth())
        self.pushButton_ex_10.setSizePolicy(sizePolicy)
        self.pushButton_ex_10.setObjectName("pushButton_ex_10")
        self.horizontalLayout_19.addWidget(self.pushButton_ex_10)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.lineEdit_ex_11 = QtWidgets.QLineEdit(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ex_11.sizePolicy().hasHeightForWidth())
        self.lineEdit_ex_11.setSizePolicy(sizePolicy)
        self.lineEdit_ex_11.setObjectName("lineEdit_ex_11")
        self.horizontalLayout_20.addWidget(self.lineEdit_ex_11)
        self.pushButton_ex_11 = QtWidgets.QPushButton(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ex_11.sizePolicy().hasHeightForWidth())
        self.pushButton_ex_11.setSizePolicy(sizePolicy)
        self.pushButton_ex_11.setObjectName("pushButton_ex_11")
        self.horizontalLayout_20.addWidget(self.pushButton_ex_11)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.lineEdit_ex_12 = QtWidgets.QLineEdit(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ex_12.sizePolicy().hasHeightForWidth())
        self.lineEdit_ex_12.setSizePolicy(sizePolicy)
        self.lineEdit_ex_12.setObjectName("lineEdit_ex_12")
        self.horizontalLayout_21.addWidget(self.lineEdit_ex_12)
        self.pushButton_ex_12 = QtWidgets.QPushButton(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ex_12.sizePolicy().hasHeightForWidth())
        self.pushButton_ex_12.setSizePolicy(sizePolicy)
        self.pushButton_ex_12.setObjectName("pushButton_ex_12")
        self.horizontalLayout_21.addWidget(self.pushButton_ex_12)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.lineEdit_ex_13 = QtWidgets.QLineEdit(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ex_13.sizePolicy().hasHeightForWidth())
        self.lineEdit_ex_13.setSizePolicy(sizePolicy)
        self.lineEdit_ex_13.setObjectName("lineEdit_ex_13")
        self.horizontalLayout_22.addWidget(self.lineEdit_ex_13)
        self.pushButton_ex_13 = QtWidgets.QPushButton(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ex_13.sizePolicy().hasHeightForWidth())
        self.pushButton_ex_13.setSizePolicy(sizePolicy)
        self.pushButton_ex_13.setObjectName("pushButton_ex_13")
        self.horizontalLayout_22.addWidget(self.pushButton_ex_13)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.lineEdit_ex_14 = QtWidgets.QLineEdit(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ex_14.sizePolicy().hasHeightForWidth())
        self.lineEdit_ex_14.setSizePolicy(sizePolicy)
        self.lineEdit_ex_14.setObjectName("lineEdit_ex_14")
        self.horizontalLayout_23.addWidget(self.lineEdit_ex_14)
        self.pushButton_ex_14 = QtWidgets.QPushButton(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ex_14.sizePolicy().hasHeightForWidth())
        self.pushButton_ex_14.setSizePolicy(sizePolicy)
        self.pushButton_ex_14.setObjectName("pushButton_ex_14")
        self.horizontalLayout_23.addWidget(self.pushButton_ex_14)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.lineEdit_ex_15 = QtWidgets.QLineEdit(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ex_15.sizePolicy().hasHeightForWidth())
        self.lineEdit_ex_15.setSizePolicy(sizePolicy)
        self.lineEdit_ex_15.setObjectName("lineEdit_ex_15")
        self.horizontalLayout_24.addWidget(self.lineEdit_ex_15)
        self.pushButton_ex_15 = QtWidgets.QPushButton(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ex_15.sizePolicy().hasHeightForWidth())
        self.pushButton_ex_15.setSizePolicy(sizePolicy)
        self.pushButton_ex_15.setObjectName("pushButton_ex_15")
        self.horizontalLayout_24.addWidget(self.pushButton_ex_15)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.lineEdit_ex_16 = QtWidgets.QLineEdit(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ex_16.sizePolicy().hasHeightForWidth())
        self.lineEdit_ex_16.setSizePolicy(sizePolicy)
        self.lineEdit_ex_16.setObjectName("lineEdit_ex_16")
        self.horizontalLayout_25.addWidget(self.lineEdit_ex_16)
        self.pushButton_ex_16 = QtWidgets.QPushButton(self.tab_more_cmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ex_16.sizePolicy().hasHeightForWidth())
        self.pushButton_ex_16.setSizePolicy(sizePolicy)
        self.pushButton_ex_16.setObjectName("pushButton_ex_16")
        self.horizontalLayout_25.addWidget(self.pushButton_ex_16)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_25)
        self.verticalLayout_5.addLayout(self.horizontalLayout_31)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab_more_cmd, "")
        self.verticalLayout_7.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit_output_hex = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_output_hex.setInputMethodHints(QtCore.Qt.ImhNone)
        self.textEdit_output_hex.setReadOnly(True)
        self.textEdit_output_hex.setObjectName("textEdit_output_hex")
        self.horizontalLayout.addWidget(self.textEdit_output_hex)
        self.textEdit_output_str = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_output_str.setInputMethodHints(QtCore.Qt.ImhNone)
        self.textEdit_output_str.setReadOnly(True)
        self.textEdit_output_str.setObjectName("textEdit_output_str")
        self.horizontalLayout.addWidget(self.textEdit_output_str)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 868, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_send.clicked.connect(MainWindow.data_send)
        self.pushButton_Open.clicked.connect(MainWindow.hid_dev_open)
        self.comboBox_hid_devices.activated['QString'].connect(MainWindow.hid_devices_actived)
        self.pushButton_refresh.clicked.connect(MainWindow.hid_dev_refresh)
        self.pushButton_copy_path.released.connect(MainWindow.copy_dev_path_released)
        self.checkBox_hex.toggled['bool'].connect(MainWindow.hex_send_toggle)
        self.checkBox_timer.toggled['bool'].connect(MainWindow.timer_send_toggle)
        self.pushButton_copy_path.pressed.connect(MainWindow.copy_dev_path_pressed)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "VID"))
        self.label_3.setText(_translate("MainWindow", "Vendor Name "))
        self.label_2.setText(_translate("MainWindow", "PID"))
        self.label_4.setText(_translate("MainWindow", "Product Name"))
        self.label_5.setText(_translate("MainWindow", "Serial Number"))
        self.pushButton_refresh.setText(_translate("MainWindow", "Refresh"))
        self.pushButton_copy_path.setText(_translate("MainWindow", "Copy Device Path"))
        self.pushButton_Open.setText(_translate("MainWindow", "Open"))
        self.checkBox_hex.setText(_translate("MainWindow", "HEX Send   "))
        self.label_7.setText(_translate("MainWindow", "Report ID"))
        self.checkBox_timer.setText(_translate("MainWindow", "Timer Send"))
        self.label_6.setText(_translate("MainWindow", "Time(ms)"))
        self.pushButton_send.setText(_translate("MainWindow", "Send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_one_cmd), _translate("MainWindow", "Command Send"))
        self.pushButton_ex_1.setText(_translate("MainWindow", "1"))
        self.pushButton_ex_2.setText(_translate("MainWindow", "2"))
        self.pushButton_ex_3.setText(_translate("MainWindow", "3"))
        self.pushButton_ex_4.setText(_translate("MainWindow", "4"))
        self.pushButton_ex_5.setText(_translate("MainWindow", "5"))
        self.pushButton_ex_6.setText(_translate("MainWindow", "6"))
        self.pushButton_ex_7.setText(_translate("MainWindow", "7"))
        self.pushButton_ex_8.setText(_translate("MainWindow", "8"))
        self.pushButton_ex_9.setText(_translate("MainWindow", "9"))
        self.pushButton_ex_10.setText(_translate("MainWindow", "10"))
        self.pushButton_ex_11.setText(_translate("MainWindow", "11"))
        self.pushButton_ex_12.setText(_translate("MainWindow", "12"))
        self.pushButton_ex_13.setText(_translate("MainWindow", "13"))
        self.pushButton_ex_14.setText(_translate("MainWindow", "14"))
        self.pushButton_ex_15.setText(_translate("MainWindow", "15"))
        self.pushButton_ex_16.setText(_translate("MainWindow", "16"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_more_cmd), _translate("MainWindow", "More Commands"))

